swagger: '2.0'

info:
  title: Careers API
  version: '1.0'

basePath: /api/v1

paths:
  /jobs:
    get:
      tags:
        - Careers
      description: "Get all `job` objects. Can be filtered by parameters."
      operationId: getJobs
      produces:
        - application/json
      parameters:
        - name: location
          in: query
          required: false
          type: string
          description: "Filter by city/state; e.g. corvallis, OR"
        - name: positionType
          in: query
          required: false
          type: string
          description: "Filter by position type; e.g. full-time"
        - name: positionTitle
          in: query
          required: false
          type: string
        - name: employer
          in: query
          required: false
          type: string
        - name: hideExpiredJobs
          in: query
          required: false
          type: boolean
        - name: page[size]
          description: "Number of results to return. Used in pagination. Default value is 10."
          in: query
          required: false
          type: integer
          format: int32
        - name: page[number]
          description: "Page number of results. Used to paginate through results."
          in: query
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: "Successful response"
          schema:
            $ref: '#/definitions/ResultObjects'
        404:
          description: "Not found"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/Error"

  /jobs/{jobId}:
    get:
      tags:
        - Careers
      description: "Get a job object by jobId"
      operationId: getJobById
      produces:
        - application/json
      parameters:
        - name: jobId
          in: path
          required: true
          type: integer
          format: int32
      responses:
        200:
          description: "Successful response"
          schema:
            $ref: "#/definitions/ResultObject"
        404:
          description: "Not found"
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/Error"

definitions:
  ResultObject:
      properties:
        links:
          $ref: "#/definitions/Links"
        data:
          $ref: "#/definitions/ResourceObject"

  ResultObjects:
    properties:
      links:
        $ref: "#/definitions/Links"
      data:
        type: array
        items:
          $ref: "#/definitions/ResourceObject"

  ResourceObject:
    properties:
      id:
        type: integer
        format: int32
      type:
        type: string
      attributes:
        $ref: "#/definitions/Attributes"

  Attributes:
    type: object
    properties:
      OrganizationName:
        type: string
        description: "Name of the employer"
      PositionTitle:
        type: string
      HowtoApply:
        type: string
      PositionLocation:
        type: string
        description: "(City, State)"
      PositionFunction:
        type: string
      PositionType:
        type: string
        description: "Full-time/Part-time/Internship - Paid"
      ExpirationDate:
        type: string
        format: date
      JobLink:
        type: string

  Links:
    properties:
      self:
        type: string
      first:
        type: string
      last:
        type: string
      prev:
        type: string
      next:
        type: string

  Error:
    type: object
    properties:
      status:
        type: integer
        format: int32
      developerMessage:
        type: string
      userMesage:
        type: string
      code:
        type: integer
      details:
        type: string
